/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
static yyconst short int yy_accept[407] =
    {   0,
        0,    0,  120,  118,  116,  115,  103,  118,  118,   99,
      104,  118,   83,   84,   97,   95,   79,   96,   80,   98,
      106,  106,   77,   78,  100,  102,  101,  109,  109,  109,
      109,   81,   82,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,   85,  118,
       86,  116,   92,    0,  111,    0,   93,    0,  117,  110,
        9,   87,   88,  107,    7,    8,  107,  112,  112,  112,
      106,   89,   91,   90,  109,  114,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,   23,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,

      109,   24,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,   94,  111,    0,    0,  107,    0,    8,  107,
        0,  108,  112,  109,   12,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,   21,  109,  109,  109,  109,  109,
      109,  109,  109,  109,   16,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,    0,  105,  105,
        0,  108,  113,  108,  113,   11,  109,   18,  109,   27,

       19,  109,  109,  109,  109,  109,  109,  109,   25,  109,
      109,   38,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,   69,   71,  109,   20,  109,
      109,   72,   74,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,   33,  109,  109,   15,
      109,  109,  109,    0,  105,  105,  109,   30,  109,   32,
      109,  109,   14,  109,  109,   34,  109,  109,  109,   65,
      109,   66,   42,  109,   67,   68,   43,  109,  109,   45,
      109,   47,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,   63,  109,  109,  109,  109,  109,  109,  109,

      109,  109,  109,  109,  109,   22,    0,   10,  109,  109,
      109,  109,   17,   36,   39,   40,  109,  109,  109,   62,
      109,   48,  109,  109,   76,   57,  109,   49,   50,   29,
       51,   52,  109,  109,   64,   35,   26,  109,   55,   75,
      109,  109,  109,    0,  109,  109,   28,  109,   41,   56,
       44,   46,   70,  109,   73,   53,   58,   54,  109,   60,
      109,    5,    5,   37,   31,  109,    0,   59,   61,    0,
        0,  109,    0,    0,    0,  109,    0,    0,    0,  109,
        0,    0,    0,   13,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    3,    0,    0,    1,

        4,    0,    2,    0,    6,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   28,   27,
       29,   30,   31,   27,   27,   32,   27,   27,   33,   34,
       27,   27,   27,   35,   36,   27,   37,   27,   27,   27,
       38,    1,   39,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   27,   50,   51,   52,   53,
       54,   55,   27,   56,   57,   58,   59,   60,   61,   27,
       62,   27,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    3,    4,    1,    5,    5,
        1,    1,    1,    1,    1,    6,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    6,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1
    } ;

static yyconst short int yy_base[416] =
    {   0,
        0,    0,  807,  808,   64,  808,  782,  799,  749,  808,
      794,   61,  808,  808,  784,  787,  808,  784,   50,   59,
       56,   61,  808,  808,  775,  774,  773,  770,   48,   57,
       56,  808,  808,   59,   68,   69,   60,   98,   62,   74,
       67,   72,   65,  103,   78,   79,  111,   73,  808,  731,
      808,  131,  808,  788,  808,  737,  808,  782,  781,  808,
      808,  808,  808,  150,  808,    0,  154,  160,  773,  167,
      172,  808,  808,  808,  763,  762,  121,   71,   61,   86,
      149,  136,  110,  158,  123,  164,  116,  159,  170,  146,
      172,  175,  181,  176,  178,  180,  183,  198,  185,  182,

      186,  761,  194,  196,  190,   76,  187,  209,  199,  193,
      200,  216,  222,  223,  224,  227,  228,  229,  231,  232,
      234,  238,  808,  808,  745,  246,  254,  276,    0,  274,
      249,  281,  289,  251,  759,  278,  259,  280,  271,  257,
      281,  285,  288,  289,  291,  292,  294,  297,  298,  299,
      300,  301,  305,  302,  758,  306,  307,  310,  309,  312,
      311,  318,  315,  320,  757,  322,  323,  327,  333,  335,
      340,  342,  343,  349,  351,  348,  357,  356,  352,  359,
      358,  361,  360,  365,  368,  362,  369,  735,  402,  406,
      413,  380,  420,  388,  394,  755,  402,  754,  398,  753,

      752,  404,  405,  409,  378,  415,  416,  417,  751,  419,
      418,  750,  424,  423,  426,  420,  429,  427,  421,  430,
      433,  440,  436,  425,  431,  445,  749,  428,  748,  441,
      446,  453,  747,  462,  466,  468,  470,  471,  472,  473,
      474,  476,  477,  482,  479,  480,  746,  481,  483,  745,
      484,  485,  488,  718,  521,  525,  500,  743,  504,  742,
      490,  510,  741,  521,  520,  740,  522,  524,  525,  739,
      527,  738,  737,  526,  736,  735,  734,  529,  530,  733,
      528,  732,  532,  531,  534,  533,  537,  538,  540,  542,
      543,  544,  731,  545,  549,  560,  564,  566,  567,  568,

      569,  571,  572,  573,  574,  730,  714,  728,  576,  575,
      577,  578,  727,  726,  725,  724,  579,  580,  585,  723,
      583,  722,  581,  594,  721,  720,  586,  719,  718,  717,
      716,  715,  587,  597,  714,  713,  712,  596,  711,  710,
      590,  604,  591,  731,  602,  618,  708,  619,  707,  706,
      705,  704,  703,  642,  702,  701,  700,  699,  621,  698,
      625,  808,  455,  697,  696,  626,  698,  690,  687,  656,
      650,  627,  644,  625,  633,  628,  625,  624,  634,  629,
      634,  634,  622,  647,  613,  625,  665,  616,  658,  607,
      607,  465,  611,  407,  613,  350,  808,  259,  217,  808,

      808,  166,  808,  113,  808,  808,  686,  692,  695,  696,
      702,  706,  709,   98,  714
    } ;

static yyconst short int yy_def[416] =
    {   0,
      406,    1,  406,  406,  406,  406,  406,  407,  406,  406,
      406,  408,  406,  406,  406,  406,  406,  406,  406,  406,
      409,  409,  406,  406,  406,  406,  406,  410,  410,  410,
      410,  406,  406,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  406,  406,
      406,  406,  406,  407,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  411,  406,  409,  409,  412,
      409,  406,  406,  406,  410,  406,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  406,  406,  406,  406,  406,  413,  411,  406,
      414,  409,  412,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  406,  406,  406,
      413,  406,  413,  406,  414,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  406,  406,  406,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  406,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  415,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  406,  406,  410,  410,  410,  406,  410,  410,  406,
      406,  410,  406,  406,  406,  410,  406,  406,  406,  410,
      406,  406,  406,  410,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,    0,  406,  406,  406,  406,
      406,  406,  406,  406,  406
    } ;

static yyconst short int yy_nxt[874] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,    4,   28,   28,   28,   29,
       28,   30,   31,   28,   28,   28,   28,   32,   33,   28,
       28,   34,   35,   36,   37,   38,   39,   28,   40,   28,
       28,   28,   41,   28,   42,   43,   44,   45,   46,   47,
       48,   28,   49,   50,   51,   52,   59,   52,   64,   64,
       60,   65,   67,   76,   68,   68,   66,   67,   77,   71,
       71,   76,   76,   70,   76,   76,   76,   76,   70,   78,
       76,   79,   76,   76,   76,  136,   76,   76,   76,   76,

       70,   76,  195,   76,   76,   70,  101,  135,   82,  108,
       89,   76,   80,   86,   81,   83,  105,   87,   84,  102,
      122,   85,   88,   76,  168,  104,  103,  106,   76,  115,
      107,  117,   52,  116,   52,   76,   76,  405,   90,  137,
       91,   76,   92,   93,   94,  109,   76,  110,   76,  134,
      140,   95,   96,   97,   98,   99,  118,  111,  100,  112,
      113,   76,  145,  114,  119,  120,  126,  121,  127,  127,
      126,   76,  130,  130,   76,  142,   67,  128,   68,   68,
      131,  128,  131,   76,   76,  132,  132,   70,   67,   76,
       71,   71,  139,  138,  128,   76,  148,   76,  128,   70,

       76,   76,  141,   76,   70,   76,   76,   76,   76,  143,
       76,   76,   76,  404,  144,   76,   70,  146,   76,   76,
      153,   76,  149,   76,   76,   76,  147,  158,  150,  161,
      151,  152,  154,  155,   76,  156,  164,  162,  157,  174,
      159,   76,  160,  163,  169,  167,  166,   76,   76,   76,
      175,  165,   76,   76,   76,  176,   76,   76,  177,   76,
      170,  171,  403,   76,  189,  189,  172,  194,  194,  173,
      190,  179,  127,  127,  182,  402,   76,  178,  180,  184,
      196,  128,   76,  183,   76,  181,  187,  185,  186,  191,
      190,  191,  130,  130,  192,  192,   76,  406,  128,  132,

      132,  128,  406,   76,  406,   76,   76,   69,   69,  198,
       76,  197,  201,   76,   76,  200,   76,   76,  128,   76,
      199,  202,   76,   76,   76,   76,   76,   76,  205,  206,
       76,   76,   76,  208,   76,   76,   76,   76,  209,  207,
       76,  203,  204,   76,  212,   76,  216,   76,   76,  221,
      219,  211,   76,  210,  217,  213,  222,  226,   76,  214,
       76,  224,  215,  220,  218,   76,  225,   76,   76,  223,
      228,  227,  229,   76,   76,  232,   76,   76,  230,  231,
      235,   76,   76,   76,   76,   76,   76,   76,  234,  233,
       76,  237,  239,   76,   76,  401,  241,  242,  192,  192,

      236,  238,  247,   76,  245,  248,  194,  194,  250,  244,
      240,  246,  406,  406,  243,  249,  251,  252,  126,  253,
      255,  255,  126,   76,  256,  256,  406,   76,  406,   76,
       76,  192,  192,  406,   76,  406,  262,  257,  406,  406,
       76,   76,   76,   76,   76,   76,   76,  258,   76,   76,
       76,   76,   76,   76,   76,   76,   76,  261,   76,  259,
      398,   76,  260,  266,  277,   76,   76,  265,  270,  275,
       76,   76,  273,  264,  267,  282,  263,  268,   76,  269,
      271,  274,  272,  276,  278,  279,  285,   76,  283,  280,
      281,   76,  284,   76,  286,   76,   76,   76,   76,   76,

      288,   76,   76,  287,   76,   76,   76,   76,   76,   76,
       76,  370,  371,   76,  295,   76,  293,  290,  395,  298,
      301,  289,  292,  291,  299,   76,  296,  300,  297,   76,
      294,  303,  306,  305,  308,   76,  304,  190,  302,  255,
      255,  190,  310,  256,  256,   76,   76,   76,  309,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
      311,  312,   76,   76,  313,   76,  314,   76,   76,   76,
       76,  323,  316,  319,   76,  320,  322,  324,  327,  315,
      317,  321,  326,  318,  328,   76,  329,  331,  325,   76,
      332,   76,   76,   76,   76,  330,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,  333,   76,  335,
       76,   76,   76,  340,  337,   76,   76,  334,  338,   76,
      339,   76,   76,  336,  341,  350,  343,   76,  348,   76,
      342,  345,  356,  346,  347,  349,  353,  351,  354,  352,
      358,  355,  357,   76,   76,  367,   76,  359,  361,  360,
       76,   76,   76,   76,   76,  366,  396,  364,  399,  394,
      393,  392,  365,  397,  391,  400,  368,   76,  390,  389,
      369,  388,   76,  384,  387,  376,  386,  385,  383,  382,
      381,  372,  379,  378,  377,  380,   54,   54,   54,   54,
       54,   54,   58,   58,   58,   58,   58,   58,   69,   69,

       75,   75,  129,  375,  129,  129,  129,  129,  133,  374,
      133,  193,   76,  193,  362,   76,  362,  362,  362,  362,
      373,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  363,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  344,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,  307,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,  254,   76,   76,   76,  188,   76,   76,   76,  406,
       60,   60,  125,  124,  123,   76,   74,   73,   72,   63,

       62,   61,   57,   56,   55,   53,  406,    3,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406
    } ;

static yyconst short int yy_chk[874] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,   12,    5,   19,   19,
       12,   20,   21,   29,   21,   21,   20,   22,   29,   22,
       22,   31,   30,   21,   34,   37,   79,   39,   22,   30,
       43,   31,   41,   35,   36,   79,   78,   42,   48,   40,

       21,  106,  414,   45,   46,   22,   39,   78,   35,   43,
       37,   80,   34,   36,   34,   35,   42,   36,   35,   40,
       48,   35,   36,   38,  106,   41,   40,   42,   44,   45,
       42,   46,   52,   45,   52,   83,   47,  404,   38,   80,
       38,   87,   38,   38,   38,   44,   77,   44,   85,   77,
       83,   38,   38,   38,   38,   38,   47,   44,   38,   44,
       44,   82,   87,   44,   47,   47,   64,   47,   64,   64,
       67,   90,   67,   67,   81,   85,   68,   64,   68,   68,
       70,   67,   70,   84,   88,   70,   70,   68,   71,   86,
       71,   71,   82,   81,   64,   89,   90,   91,   67,   71,

       92,   94,   84,   95,   68,   96,   93,  100,   97,   86,
       99,  101,  107,  402,   86,  105,   71,   88,  110,  103,
       94,  104,   91,   98,  109,  111,   89,   97,   92,   99,
       92,   93,   95,   95,  108,   96,  103,  100,   96,  109,
       98,  112,   98,  101,  107,  105,  104,  113,  114,  115,
      110,  103,  116,  117,  118,  111,  119,  120,  112,  121,
      108,  108,  399,  122,  126,  126,  108,  131,  131,  108,
      127,  114,  127,  127,  117,  398,  134,  113,  115,  119,
      134,  127,  140,  118,  137,  116,  122,  120,  121,  128,
      130,  128,  130,  130,  128,  128,  139,  132,  127,  132,

      132,  130,  133,  136,  133,  138,  141,  133,  133,  137,
      142,  136,  140,  143,  144,  139,  145,  146,  130,  147,
      138,  141,  148,  149,  150,  151,  152,  154,  143,  144,
      153,  156,  157,  146,  159,  158,  161,  160,  147,  145,
      163,  142,  142,  162,  150,  164,  154,  166,  167,  159,
      158,  149,  168,  148,  156,  151,  160,  163,  169,  152,
      170,  161,  153,  158,  157,  171,  162,  172,  173,  160,
      164,  163,  166,  176,  174,  169,  175,  179,  167,  168,
      171,  178,  177,  181,  180,  183,  182,  186,  170,  169,
      184,  173,  175,  185,  187,  396,  176,  177,  192,  192,

      172,  174,  181,  205,  180,  182,  194,  194,  184,  179,
      175,  180,  195,  195,  178,  183,  185,  186,  189,  187,
      189,  189,  190,  199,  190,  190,  191,  197,  191,  202,
      203,  191,  191,  193,  204,  193,  205,  197,  193,  193,
      206,  207,  208,  211,  210,  216,  219,  199,  214,  213,
      224,  215,  218,  228,  217,  220,  225,  204,  221,  202,
      394,  223,  203,  210,  219,  222,  230,  208,  215,  218,
      226,  231,  216,  207,  211,  224,  206,  213,  232,  214,
      215,  217,  215,  218,  220,  221,  228,  234,  225,  222,
      223,  235,  226,  236,  230,  237,  238,  239,  240,  241,

      232,  242,  243,  231,  245,  246,  248,  244,  249,  251,
      252,  363,  363,  253,  240,  261,  238,  235,  392,  243,
      246,  234,  237,  236,  244,  257,  241,  245,  242,  259,
      239,  249,  253,  252,  257,  262,  251,  255,  248,  255,
      255,  256,  261,  256,  256,  265,  264,  267,  259,  268,
      269,  274,  271,  281,  278,  279,  284,  283,  286,  285,
      262,  264,  287,  288,  265,  289,  267,  290,  291,  292,
      294,  284,  269,  278,  295,  279,  283,  285,  288,  268,
      271,  281,  287,  274,  289,  296,  290,  292,  286,  297,
      294,  298,  299,  300,  301,  291,  302,  303,  304,  305,

      310,  309,  311,  312,  317,  318,  323,  295,  321,  297,
      319,  327,  333,  302,  299,  341,  343,  296,  300,  324,
      301,  338,  334,  298,  303,  318,  305,  345,  312,  342,
      304,  309,  333,  310,  311,  317,  323,  319,  324,  321,
      338,  327,  334,  346,  348,  354,  359,  341,  343,  342,
      361,  366,  372,  376,  380,  348,  393,  345,  395,  391,
      390,  389,  346,  393,  388,  395,  359,  354,  387,  386,
      361,  385,  384,  380,  383,  372,  382,  381,  379,  378,
      377,  366,  375,  374,  373,  376,  407,  407,  407,  407,
      407,  407,  408,  408,  408,  408,  408,  408,  409,  409,

      410,  410,  411,  371,  411,  411,  411,  411,  412,  370,
      412,  413,  369,  413,  415,  368,  415,  415,  415,  415,
      367,  365,  364,  360,  358,  357,  356,  355,  353,  352,
      351,  350,  349,  347,  344,  340,  339,  337,  336,  335,
      332,  331,  330,  329,  328,  326,  325,  322,  320,  316,
      315,  314,  313,  308,  307,  306,  293,  282,  280,  277,
      276,  275,  273,  272,  270,  266,  263,  260,  258,  254,
      250,  247,  233,  229,  227,  212,  209,  201,  200,  198,
      196,  188,  165,  155,  135,  125,  102,   76,   75,   69,
       59,   58,   56,   54,   50,   28,   27,   26,   25,   18,

       16,   15,   11,    9,    8,    7,    3,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 3 "scanner.l"
  #include <stdio.h>
  #include <string.h>
  #include <stdlib.h>
  #include "parser.tab.h"

  int numLines = 0; // Count the number of lines of the input file.
  char line[1000] = ""; // Buffer for the texts of a line.

  // Type of tokens.
  typedef enum {key, id, op, punc, integer, doub, ch, sci, str, nl, noth, error} Type;
  typedef enum {false, true} bool; // Boolean algebra.

  void print(Type type); // Print out the output messages.

  bool inComment = false; // See if the current position is in a comment.
  bool mulComment = false; // See which type of comment.
  bool inError = false; // See if encounter error.
  bool sourceOn = true; // Control pragma source on or off.
  bool tokenOn = true; // Control pragma token on or off.
#line 713 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 31 "scanner.l"


#line 867 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 407 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 808 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "scanner.l"
{sourceOn = true;
                     print(noth);
                     return PRAGMA;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "scanner.l"
{sourceOn = false;
                      print(noth);
                      return PRAGMA;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "scanner.l"
{tokenOn = true;
                    print(noth);
                    return PRAGMA;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "scanner.l"
{tokenOn = false;
                     print(noth);
                     return PRAGMA;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "scanner.l"
{print(error);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "scanner.l"
{print(noth);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "scanner.l"
{inComment = true;
      mulComment = true;
      print(noth);
      return COMMENT_START;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "scanner.l"
{inComment = true;
        mulComment = false;
        print(noth);
        return COMMENT_SINGLE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "scanner.l"
{inComment = false;
      mulComment = false;
      print(noth);
      return COMMENT_END;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "scanner.l"
{print(noth);
          yylval.intVal = 1;
          return INT_CONSTANT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "scanner.l"
{print(noth);
        yylval.intVal = 1;
        return INT_CONSTANT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "scanner.l"
{print(noth);
       yylval.intVal = 0;
       return INT_CONSTANT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "scanner.l"
{print(id);
                return DIGITALWRITE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 "scanner.l"
{print(id);
         return DELAY;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "scanner.l"
{print(key);
        return VOIDTYPE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "scanner.l"
{print(key);
       return INTTYPE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "scanner.l"
{print(key);
          return DOUBLETYPE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "scanner.l"
{print(key);
        return BOOLTYPE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "scanner.l"
{print(key);
        return CHARTYPE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 87 "scanner.l"
{print(key);
        yylval.intVal = 0;
        return INT_CONSTANT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "scanner.l"
{print(key);
      return FOR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "scanner.l"
{print(key);
         return WHILE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 "scanner.l"
{print(key);
      return DO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "scanner.l"
{print(key);
      return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "scanner.l"
{print(key);
        return ELSE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 "scanner.l"
{print(key);
          return SWITCH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 105 "scanner.l"
{print(key);
        return CASE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "scanner.l"
{print(key);
           return DEFAULT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "scanner.l"
{print(key);
          return RETURN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 113 "scanner.l"
{print(key);
         return BREAK;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "scanner.l"
{print(key);
            return CONTINUE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "scanner.l"
{print(key);
         return CONST;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 121 "scanner.l"
{print(key);
        yylval.intVal = 1;
        return BOOL_CONSTANT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "scanner.l"
{print(key);
         yylval.intVal = 0;
         return BOOL_CONSTANT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 133 "scanner.l"
{print(key);
            return ID;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 135 "scanner.l"
{print(key);
        return ID;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 137 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 139 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 141 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 143 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 145 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 151 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 153 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 157 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 159 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 161 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 163 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 165 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 167 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 169 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 171 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 173 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 175 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 177 "scanner.l"
{print(key);
            return ID;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 179 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 181 "scanner.l"
{print(key);
            return ID;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 183 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 185 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 187 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 189 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 191 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 193 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 195 "scanner.l"
{print(key);
         return ID;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 197 "scanner.l"
{print(key);
        return ID;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 199 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 201 "scanner.l"
{print(key);
        return ID;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 203 "scanner.l"
{print(key);
        return ID;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "scanner.l"
{print(key);
           return ID;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 207 "scanner.l"
{print(key);
        return ID;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 209 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 211 "scanner.l"
{print(key);
          return ID;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 214 "scanner.l"
{print(punc);
     return ':';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 216 "scanner.l"
{print(punc);
     return ';';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 218 "scanner.l"
{print(punc);
     return ',';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 220 "scanner.l"
{print(punc);
     return '.';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 222 "scanner.l"
{print(punc);
     return '[';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 224 "scanner.l"
{print(punc);
     return ']';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 226 "scanner.l"
{print(punc);
     return '(';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 228 "scanner.l"
{print(punc);
     return ')';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 230 "scanner.l"
{print(punc);
     return '{';}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 232 "scanner.l"
{print(punc);
     return '}';}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 235 "scanner.l"
{print(op);
      return PLUSPLUS;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 237 "scanner.l"
{print(op);
      return MINUSMINUS;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 239 "scanner.l"
{print(op);
      return LESSEQUAL;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 241 "scanner.l"
{print(op);
      return MOREEQUAL;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 243 "scanner.l"
{print(op);
      return EQUALEQUAL;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 245 "scanner.l"
{print(op);
      return NOTEQUAL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 247 "scanner.l"
{print(op);
      return ANDAND;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 249 "scanner.l"
{print(op);
      return OROR;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 251 "scanner.l"
{print(op);
     return '+';}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 253 "scanner.l"
{print(op);
     return '-';}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 255 "scanner.l"
{print(op);
     return '*';}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 257 "scanner.l"
{print(op);
     return '/';}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 259 "scanner.l"
{print(op);
     return '%';}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 261 "scanner.l"
{print(op);
     return '<';}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 263 "scanner.l"
{print(op);
     return '>';}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 265 "scanner.l"
{print(op);
     return '=';}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 267 "scanner.l"
{print(op);
     return '!';}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 269 "scanner.l"
{print(op);
     return '&';}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 272 "scanner.l"
{print(error);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 274 "scanner.l"
{print(integer);
           yylval.intVal = atoi(yytext);
           return INT_CONSTANT;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 278 "scanner.l"
{print(doub);
          yylval.doubVal = atof(yytext);
          return DOUB_CONSTANT;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 282 "scanner.l"
{print(sci);
       yylval.doubVal = atof(yytext);
       return DOUB_CONSTANT;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 286 "scanner.l"
{print(id);
      yylval.strVal = yytext;
      return ID;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 290 "scanner.l"
{print(ch);
           yylval.charVal = yytext[0];
           return CHAR_CONSTANT;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 294 "scanner.l"
{print(str);
                  yylval.strVal = yytext;
                  return STR_CONSTANT;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 298 "scanner.l"
{print(error);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 299 "scanner.l"
{print(error);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 300 "scanner.l"
{print(error);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 302 "scanner.l"
{inComment = (mulComment == true) ? true : false;
    mulComment = (inComment == 1) ? true : false;
    print(nl);
    strcpy(line, "");}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 307 "scanner.l"
{print(noth);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 308 "scanner.l"
{print(noth);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 309 "scanner.l"
{print(error);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 311 "scanner.l"
ECHO;
	YY_BREAK
#line 1678 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 407 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 407 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 406);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 311 "scanner.l"


int yywrap()
{
  return 1; // EOF
}

void print(Type type)
{
  switch(type)
  {
    case key:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#key:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case id:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#id:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case op:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#op:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case punc:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#punc:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case integer:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#integer:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case doub:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#double:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case ch:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#char:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case sci:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#sci:%s\n", yytext);
      }
      strcat(line, yytext);
      break;

    case str:
      if (inComment == false && inError == false && tokenOn == true)
      {
        char printStr[1000];
        strncpy(printStr, yytext + 1, yyleng - 2);
        printStr[yyleng - 2] = '\0';
        printf("#string:%s\n", printStr);
      }
      strcat(line, yytext);
      break;

    case nl:
      if (inError == false && sourceOn == true)
      {
        printf("%d:%s\n", ++numLines, line);
        break;
      }
      else if (inError == false && sourceOn == false)
      {
        ++numLines;
        break;
      }
      else if (inError == true)
      {
        fprintf(stderr, "Error at line %d: %s\n", ++numLines, line);
        exit(1);
      }
      else
      {
        break;
      }

    case noth:
      strcat(line, yytext);
      break;

    case error:
      if (inComment == true)
      {
        break;
      }
      else
      {
        if (inError == false)
        {
          inError = true;
          printf("Error: %s\n", yytext);
          strcpy(line, yytext);
        }
        else
        {
          strcat(line, yytext);
        }
      }
  }
}